### ISSUE TITLE
EXT-X-VERSION for EXT-X-PRELOAD-HINT should be 10 at least

### ISSUE THREAD

**Issue by hsnks100** [bluenviron/gohlslib#144]
following https://developer.apple.com/documentation/http-live-streaming/about-the-ext-x-version-tag

<img width="928" alt="image" src="https://github.com/bluenviron/gohlslib/assets/3623889/ed9e65df-11f0-49c1-93f9-638ff1fda348">

So, gohlslib EXT-X-VERSION should be 10 at least.

**Comment by aler9** [comment]
Hello, thanks for reporting this issue. The reason why the Apple specification was not followed is that is it not among the specifications that we are following, that are listed in the [README](https://github.com/bluenviron/gohlslib?tab=readme-ov-file#specifications).

After some reasoning i decided to start following the Apple specification and include in in the list of supported specifications, in order to better support Apple devices.
